 rem Generated 12/3/2017 10:17:28 AM by Visual bB Version 1.0.0.554
 rem Atari racing game created for Georgia Tech LMC 2700 Fall 2017
 rem Created By: Alexus Clark, Ye-Ji Kim, Kevin Tang

 set romsize = 2k
 
 rem player sprites
 player0:
 %11000011
 %11000011
 %11000011
 %11111111
 %11111111
 %11111111
 %11111111
 %11111111
 %11111111
 %11000011
 %11000011
 %11000011
end
 player0color:
 $02;
 $02;
 $F6;
 $F6;
 $0C;
 $A0;
 $A0;
 $0E;
 $F6;
 $F6;
 $02;
 $02;
end

 player1:
 %11000011
 %11000011
 %11000011
 %11111111
 %11111111
 %11111111
 %11111111
 %11111111
 %11111111
 %11000011
 %11000011
 %11000011
end
 player1color:
 $02;
 $02;
 $40;
 $40;
 $0C;
 $00;
 $00;
 $0E;
 $40;
 $40;
 $02;
 $02;
end

 rem Idle start screen
startscreen
 
 set kernel_options player1colors playercolors pfcolors
 pfcolors:
 6
 196
 28
 28
 28
 28
 28
 28
 28
 196
 196
 6
end
 
 playfield:
 ................................
 ................................
 ................................
 ................................
 ......X...............XX........
 .....XX..............X..X.......
 ......X................X........
 ......X...............X.........
 ....XXXXX............XXXX.......
 ................................
 ................................
end

 f = f + 1
 if f = 61 then f = 12

 player0x=40:player0y=85
 player1x=105:player1y=85
 drawscreen
 if joy0fire then goto gamestart
 goto startscreen

gamestart
 const pfscore = 1

 pfscorecolor = $9c
 pfscore1 = %00000000
 pfscore2 = %00000000

 player0x=50:player0y=40
 player1x=50:player1y=60
 g = 0
 ballheight = 4
 CTRLPF = $21
 h = 1


 rem start of the main draw loop
sprites
 f = f + 1
 g = g + 1
 
 rem animation of the street passing by
 if f = 20 || f = 45 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ..............................XX
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 21 || f = 46 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ............................XX..
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end

 if f = 22 || f = 47 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ..........................XX....
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 23 || f = 48 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ........................XX......
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 24 || f = 49 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ......................XX........
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 25 || f = 50 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ....................XX..........
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 26 || f = 51 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ..................XX............
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 27 || f = 52 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ................XX..............
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 28 || f = 53 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ..............XX................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 29 || f = 54 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ............XX..................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 30 || f = 55 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ..........XX....................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 31 || f = 56 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ........XX......................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 
 if f = 32 || f = 57 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ......XX........................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 33 || f = 58 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ....XX..........................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end

 if f = 34 || f = 59 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ..XX............................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 35 || f = 60 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 XX..............................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end
 if f = 36 || f = 61 then playfield: 
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
 ................................
 ................................
 ................................
 ................................
 ................................
 ................................
 XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 ................................
end

 if f = 61 then f = 12
 if g = 50 then g = 49
 
 rem spawn ball at random location based on f
 if g = 48 then ballx = 150:bally = f + 10
 
draw_loop
 drawscreen
 
 rem ball movement
 ballx = ballx - 1
 if g > 48 then bally = bally + h

 rem player movement 
 if joy0up && player0y > 24 then player0y = player0y-1
 if joy0down && player0y < 72 then player0y = player0y+1
 if joy0left && player0x > 16 then player0x = player0x-1
 if joy0right && player0x < 138 then player0x = player0x+1

 if joy1up && player1y > 28 then player1y = player1y-1
 if joy1down && player1y < 72 then player1y = player1y+1
 if joy1left && player1x > 16 then player1x = player1x-1
 if joy1right && player1x < 138 then player1x = player1x+1

 if bally = 20 then h = 1
 if bally = 72 then h = -1

 if ballx = 10 then g = 0: bally = -50

 rem collision detection
 if collision(player0, player1) then score = score + 1:player0x = player0x - (player1x - player0x):player1x = player1x - (player0x - player1x)
 if collision(player0, player1) then player0y = player0y - (player1y - player0y):player1y = player1y - (player0y - player1y)

 if collision(player0, ball) then bally = -50:g = 0:goto ponescore
 if collision(player1, ball) then bally = -50:g = 0:goto ptwoscore

 goto sprites

ponescore
 if pfscore1 = %11011000 then pfscore1 = %11011011:goto ponevictory
 if pfscore1 = %11000000 then pfscore1 = %11011000
 if pfscore1 = %00000000 then pfscore1 = %11000000
 
 goto sprites

ptwoscore
 if pfscore2 = %11011000 then pfscore2 = %11011011:goto ptwovictory
 if pfscore2 = %11000000 then pfscore2 = %11011000
 if pfscore2 = %00000000 then pfscore2 = %11000000
 
 goto sprites

 rem victory screen for P1
ponevictory
 COLUBK = 0
 player0x = -50:player0y = -50
 player1x = -50:player1y = -50
 pfcolors:
 28
 28
 28
 28
 28
 28
 28
 28
 28
 28
 28
 28
end
 playfield:
 ................................
 XX...X.....X...X...XXX..XX..X...
 X.X.XX.....X...X....X...X.X.X...
 X.X..X.....X...X....X...X.X.X...
 XX...X.....X.X.X....X...X.X.X...
 X....X.....XX.XX....X...X..XX...
 X...XXX....X...X...XXX..X...X...
 ................................
 ................................
 ................................
 ................................
end
 drawscreen
 if joy0fire then goto startscreen
 goto ponevictory

 rem victory screen for P2
ptwovictory
 COLUBK = 0
 player0x = -50:player0y = -50
 player1x = -50:player1y = -50
 pfcolors:
 28
 28
 28
 28
 28
 28
 28
 28
 28
 28
 28
 28
end
 playfield:
 ................................
 XX...X.....X...X...XXX..XX..X...
 X.X.X.X....X...X....X...X.X.X...
 X.X...X....X...X....X...X.X.X...
 XX...X.....X.X.X....X...X.X.X...
 X...X......XX.XX....X...X..XX...
 X...XXX....X...X...XXX..X...X...
 ................................
 ................................
 ................................
 ................................
end
 drawscreen
 if joy0fire then goto startscreen
 goto ptwovictory